create extension if not exists pgcrypto;

create table if not exists public.branding_settings (
  id text primary key default 'default',
  company_name text not null default 'Lume Real Estate',
  system_name text not null default 'Brokr',
  primary_color text not null default '#bdb8b2',
  accent_color text not null default '#837a6d',
  logo_src text,
  icon_src text,
  updated_at timestamptz not null default now()
);

create table if not exists public.broker_contacts (
  id text primary key default 'primary',
  broker_name text not null,
  broker_email text not null,
  broker_phone text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.archive_settings (
  id text primary key default 'default',
  google_drive_folder_url text,
  archive_folder_name text not null default 'Brokr Closed Transaction Archives',
  package_format text not null default 'ZIP package',
  updated_at timestamptz not null default now()
);

create table if not exists public.agents (
  id bigint generated by default as identity primary key,
  profile_image_url text,
  first_name text not null,
  last_name text not null,
  email text not null unique,
  phone text,
  street text,
  city text,
  state text,
  zip text,
  calendar_color text not null default '#837a6d',
  commission_split numeric(5,2) not null default 70,
  license_file_name text,
  license_storage_path text,
  license_expires_on date,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid references auth.users(id) on delete set null,
  agent_id bigint references public.agents(id) on delete set null,
  profile_image_url text,
  email text not null unique,
  role text not null default 'Agent' check (role in ('Agent', 'Broker', 'Admin', 'Read only')),
  can_upload_files boolean not null default true,
  permission_scope text not null default 'Own transactions only' check (permission_scope in ('Own transactions only', 'Any transaction')),
  status text not null default 'Active' check (status in ('Active', 'Suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  agent_id bigint references public.agents(id) on delete set null,
  side text not null check (side in ('buyer', 'seller')),
  client_name text not null,
  client_email text,
  client_phone text,
  property_address text,
  contract_date date not null,
  list_price numeric(14,2) not null default 0,
  contract_price numeric(14,2) not null default 0,
  status text not null default 'New' check (status in ('New', 'Under Contract', 'Closing', 'Closed', 'Review Needed', 'Cancelled')),
  deadlines jsonb not null default '{}'::jsonb,
  required_documents jsonb not null default '{}'::jsonb,
  additional_documents jsonb not null default '[]'::jsonb,
  archived_at timestamptz,
  archive_destination text,
  archive_package_format text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transaction_files (
  id bigint generated by default as identity primary key,
  transaction_id bigint not null references public.transactions(id) on delete cascade,
  document_name text not null,
  document_type text not null default 'Required',
  file_name text not null,
  storage_path text,
  review_status text not null default 'Pending Review' check (review_status in ('Pending Review', 'Approved', 'Needs Correction', 'Archived')),
  uploaded_by uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.company_tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  owner text not null,
  deadline date,
  status text not null default 'Open',
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  notification_key text not null unique,
  type text not null,
  title text not null,
  detail text not null,
  status text not null default 'Open',
  action_label text,
  action_href text,
  state text not null default 'open' check (state in ('open', 'dismissed', 'approved', 'archived')),
  related_agent_id bigint references public.agents(id) on delete set null,
  related_transaction_id bigint references public.transactions(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_branding_settings_updated_at on public.branding_settings;
create trigger set_branding_settings_updated_at
before update on public.branding_settings
for each row execute function public.set_updated_at();

drop trigger if exists set_broker_contacts_updated_at on public.broker_contacts;
create trigger set_broker_contacts_updated_at
before update on public.broker_contacts
for each row execute function public.set_updated_at();

drop trigger if exists set_archive_settings_updated_at on public.archive_settings;
create trigger set_archive_settings_updated_at
before update on public.archive_settings
for each row execute function public.set_updated_at();

drop trigger if exists set_agents_updated_at on public.agents;
create trigger set_agents_updated_at
before update on public.agents
for each row execute function public.set_updated_at();

drop trigger if exists set_app_users_updated_at on public.app_users;
create trigger set_app_users_updated_at
before update on public.app_users
for each row execute function public.set_updated_at();

drop trigger if exists set_transactions_updated_at on public.transactions;
create trigger set_transactions_updated_at
before update on public.transactions
for each row execute function public.set_updated_at();

drop trigger if exists set_transaction_files_updated_at on public.transaction_files;
create trigger set_transaction_files_updated_at
before update on public.transaction_files
for each row execute function public.set_updated_at();

drop trigger if exists set_company_tasks_updated_at on public.company_tasks;
create trigger set_company_tasks_updated_at
before update on public.company_tasks
for each row execute function public.set_updated_at();

drop trigger if exists set_notifications_updated_at on public.notifications;
create trigger set_notifications_updated_at
before update on public.notifications
for each row execute function public.set_updated_at();

insert into public.branding_settings (id, company_name, system_name, primary_color, accent_color)
values ('default', 'Lume Real Estate', 'Brokr', '#bdb8b2', '#837a6d')
on conflict (id) do nothing;

insert into public.broker_contacts (id, broker_name, broker_email, broker_phone)
values ('primary', 'Jared Alvey', 'broker@lumerealestate.com', '(555) 430-1000')
on conflict (id) do nothing;

insert into public.archive_settings (id, archive_folder_name, package_format)
values ('default', 'Brokr Closed Transaction Archives', 'ZIP package')
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values
  ('branding-assets', 'branding-assets', true),
  ('profile-images', 'profile-images', true),
  ('transaction-files', 'transaction-files', false),
  ('archive-packages', 'archive-packages', false)
on conflict (id) do nothing;

alter table public.branding_settings enable row level security;
alter table public.broker_contacts enable row level security;
alter table public.archive_settings enable row level security;
alter table public.agents enable row level security;
alter table public.app_users enable row level security;
alter table public.transactions enable row level security;
alter table public.transaction_files enable row level security;
alter table public.company_tasks enable row level security;
alter table public.notifications enable row level security;

-- Prototype policies for Vercel preview. Replace with role-aware policies before production.
drop policy if exists "prototype read branding" on public.branding_settings;
create policy "prototype read branding" on public.branding_settings for select using (true);
drop policy if exists "prototype write branding" on public.branding_settings;
create policy "prototype write branding" on public.branding_settings for insert with check (true);
drop policy if exists "prototype update branding" on public.branding_settings;
create policy "prototype update branding" on public.branding_settings for update using (true);

drop policy if exists "prototype read broker contacts" on public.broker_contacts;
create policy "prototype read broker contacts" on public.broker_contacts for select using (true);
drop policy if exists "prototype write broker contacts" on public.broker_contacts;
create policy "prototype write broker contacts" on public.broker_contacts for all using (true) with check (true);

drop policy if exists "prototype read archive settings" on public.archive_settings;
create policy "prototype read archive settings" on public.archive_settings for select using (true);
drop policy if exists "prototype write archive settings" on public.archive_settings;
create policy "prototype write archive settings" on public.archive_settings for all using (true) with check (true);

drop policy if exists "prototype read agents" on public.agents;
create policy "prototype read agents" on public.agents for select using (true);
drop policy if exists "prototype write agents" on public.agents;
create policy "prototype write agents" on public.agents for all using (true) with check (true);

drop policy if exists "prototype read app users" on public.app_users;
create policy "prototype read app users" on public.app_users for select using (true);
drop policy if exists "prototype write app users" on public.app_users;
create policy "prototype write app users" on public.app_users for all using (true) with check (true);

drop policy if exists "prototype read transactions" on public.transactions;
create policy "prototype read transactions" on public.transactions for select using (true);
drop policy if exists "prototype write transactions" on public.transactions;
create policy "prototype write transactions" on public.transactions for all using (true) with check (true);

drop policy if exists "prototype read transaction files" on public.transaction_files;
create policy "prototype read transaction files" on public.transaction_files for select using (true);
drop policy if exists "prototype write transaction files" on public.transaction_files;
create policy "prototype write transaction files" on public.transaction_files for all using (true) with check (true);

drop policy if exists "prototype read company tasks" on public.company_tasks;
create policy "prototype read company tasks" on public.company_tasks for select using (true);
drop policy if exists "prototype write company tasks" on public.company_tasks;
create policy "prototype write company tasks" on public.company_tasks for all using (true) with check (true);

drop policy if exists "prototype read notifications" on public.notifications;
create policy "prototype read notifications" on public.notifications for select using (true);
drop policy if exists "prototype write notifications" on public.notifications;
create policy "prototype write notifications" on public.notifications for all using (true) with check (true);

-- Prototype storage policies for preview. Tighten private file access before production.
drop policy if exists "prototype read branding assets" on storage.objects;
create policy "prototype read branding assets" on storage.objects
for select using (bucket_id = 'branding-assets');

drop policy if exists "prototype write branding assets" on storage.objects;
create policy "prototype write branding assets" on storage.objects
for all using (bucket_id = 'branding-assets') with check (bucket_id = 'branding-assets');

drop policy if exists "prototype read profile images" on storage.objects;
create policy "prototype read profile images" on storage.objects
for select using (bucket_id = 'profile-images');

drop policy if exists "prototype write profile images" on storage.objects;
create policy "prototype write profile images" on storage.objects
for all using (bucket_id = 'profile-images') with check (bucket_id = 'profile-images');

drop policy if exists "prototype read transaction files" on storage.objects;
create policy "prototype read transaction files" on storage.objects
for select using (bucket_id in ('transaction-files', 'archive-packages'));

drop policy if exists "prototype write transaction files" on storage.objects;
create policy "prototype write transaction files" on storage.objects
for all using (bucket_id in ('transaction-files', 'archive-packages')) with check (bucket_id in ('transaction-files', 'archive-packages'));
